projects:
  - name: Pound Pong
    url:
    repo: https://github.com/negativetwelve/ping-pong-ipad
    image:
    modal: pound-pong
    description: Initially, the idea started out as a web app that would keep track of all of the Ping Pong matches that went on at the Yelp office. However, the project quickly transitioned into much more. Using an RFID scanner hooked up to an Arduino which is hooked up to the iPad, we can communicate with the application using our badges which all happen to be RFID. From there, we can 'badge' into our matches and record the winner in a seamless transaction using nothing more than our badges and a single tap to label the winner. Results are sent to a simple Flask server through a JSON API where they are stored in a Mongo Database. This was a project that I worked on with a group of 4 at our semi-annual Yelp hackathon. We had two people working on the Flask server / front-end of the website and two of us (including me) working on the iPad app and getting it to communicate with the RFID scanner.

  - name: iOS game with JSON API
    url: 
    repo: 
    modal: 
    description: I've been working on an iOS game that has a Rails JSON backend and will eventually have a web component too. Promo video and web page coming soon.

  - name: Global Snapshot
    url: http://globalsnapshot.herokuapp.com/
    repo: https://github.com/japhethwong/global-snapshot
    image: 
    modal: global-snapshot
    description: Working on a group of three at the LinkedIn Hack Day 2013, we buit a real-time Twitter and Flickr visualizer. Watch as tweets and photos fall onto the map and as the photos form a real-time stream on the sidebar. Want to see more photos? Simply expand the sidebar by pressing the toggle button on the bottom right. Hover over any of the dots to view the tweet or photo from that location. Node.js backend while working with several APIs including Google Maps, Twitter Real-time, and Flickr Real-time. Also uses Socket.io for sending the data to the browser in real-time.

  - name: Calaborate
    url: http://calaborate.herokuapp.com
    repo: https://github.com/negativetwelve/calaborate
    image: /assets/images/calaborate.png
    modal: calaborate
    description: I worked as the lead developer on a small team to develop a tool for Cal students to create meetups and study sessions to review for midterms and finals.

  - name: Appsearch.es
    url: http://appsearch.es
    repo: https://github.com/negativetwelve/appsearches
    image: /assets/images/appsearches.png
    modal: appsearches
    description: An iOS app search engine. Data is gathered using a scrapper that I built and stored in a Postgres database. Search is done by indexing the database and using Postgres built-in full-text search.

  - name: Rubik's Detection
    url:
    repo: https://github.com/negativetwelve/rubiks_detection
    image:
    modal: rubiks-detection
    description: The idea was simple, take a web camera, use it to detect the colors of a rubik's cube that a user holds up to the screen. Analyze the colors, pass the output to a solver and display the necessary steps to solve the cube. It actually worked and we won third place at a hackathon as a result. My main role was working on detecting the colors by holding up the rubik's cube to your screen.

  - name: Sound of Dub
    url: https://intense-journey-6792.herokuapp.com/
    repo: https://github.com/negativetwelve/sound-of-dub
    image: /assets/images/sound-of-dub.png
    modal: sound-of-dub
    description: A music app that I built at a hackathon. It utilizes the Soundcloud API and allows users to make and play their own playlists.

  - name: Tim Todo
    url: https://timtodo.herokuapp.com/
    repo: https://github.com/negativetwelve/Tim
    image: /assets/images/tim.png
    modal: tim
    description: A vim-style web based todo app that I built with a friend at our first ever hackathon. We won the Hilfinger Award given to us by Box at the 2012 H@B Hackjam.

  - name: markmiyashita.com
    url: http://markmiyashita.com
    repo: https://github.com/negativetwelve/markmiyashita.com
    image: /assets/images/website.png
    modal: markmiyashita
    description: My personal about me website that I have developed from scratch. It is built using Jekyll and hosted on Github Pages.

  - name: Life Logger
    url: 
    repo: https://github.com/negativetwelve/facebook-hackathon
    image: /assets/images/life-logger.png
    modal: life-logger
    description: I worked with a team of four at the 2012 Battle of the Bay Facebook Hackathon. We built an event logger for your computer that allows you to visualize and analyze your habits on the computer.

  - name: Pets Alliance
    url:
    repo: https://github.com/negativetwelve/pets-alliance
    image: /assets/images/petsalliance.png
    modal: petsalliance
    description: Half of an MMORPG that I built in the summer of 2012. The UI was never finished but the backend worked pretty well. May continue this project in the future.

  - name: bashprofile.com
    url: http://bashprofile.com
    repo: https://github.com/negativetwelve/bashprofile.com
    image: /assets/images/bashprofile.png
    modal: bashprofile
    description: A small tech blog that I built and designed.

